config/routes.rb
ESaver::Application.routes.draw do
  devise_for :users
  root "tasks#index"

  get '/tasks/new', controller: 'tasks', action: 'new', as: 'new_task'
  post '/tasks', controller: 'tasks', action: 'create', as: 'tasks'

  get '/tasks', controller: 'tasks', action: 'index'
  get '/tasks/:id', controller: 'tasks', action: 'show', as: 'task'

  get '/tasks/:id/edit', controller: 'tasks', action: 'edit', as: 'edit_task'
  patch '/tasks/:id', controller: 'tasks', action: 'update'

  delete '/tasks/:id', controller: 'tasks', action: 'destroy'

  get '/to_do_lists/new', controller: 'to_do_lists', action: 'new', as: 'new_to_do_list'
  post '/to_do_lists', controller: 'to_do_lists', action: 'create', as: 'to_do_lists'

  get '/to_do_lists', controller: 'to_do_lists', action: 'index'
  get '/to_do_lists/:id', controller: 'to_do_lists', action: 'show', as: 'to_do_list'

  get '/to_do_lists/:id/edit', controller: 'to_do_lists', action: 'edit', as: 'edit_to_do_list'
  patch '/to_do_lists/:id', controller: 'to_do_lists', action: 'update'

  delete '/to_do_lists/:id', controller: 'to_do_lists', action: 'destroy'

  get '/tips/new', controller: 'tips', action: 'new', as: 'new_tip'
  post '/tips', controller: 'tips', action: 'create', as: 'tips'

  get '/tips', controller: 'tips', action: 'index'
  get '/tips/:id', controller: 'tips', action: 'show', as: 'tip'

  get '/tips/:id/edit', controller: 'tips', action: 'edit', as: 'edit_tip'
  patch '/tips/:id', controller: 'tips', action: 'update'

  delete '/tips/:id', controller: 'tips', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :tip
  belongs_to :to_do_list


end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :to_do_lists, :through => :tasks

  validates :user_id, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true
  validates :room, :presence => true
  validates :price, :presence => true, numericality: { only_integer: true, :greater_than => -1, :less_than => 6}
  validates :saving, :presence => true, numericality: { only_integer: true, :greater_than => -1, :less_than => 6 }

end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :tips, :through => :tasks

  def z
    x = User.find(5)
    return x.name
  end

  validates :user_id, :presence => true

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tips
  has_one :to_do_list
  has_many :tasks, :through => :to_do_list
  has_many :todo_tips, :through => :tasks, :source => :tip

  after_create :create_to_do_list

  def create_to_do_list
    t = ToDoList.new
    t.user_id = id
    t.save
  end


  def this_user
    this_user = current_user.user_id
  end

  def name
    return"#{first_name} #{last_name}"
  end

   validates :first_name, :presence => true
   validates :last_name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

protect_from_forgery with: :exception


before_filter :configure_devise_params, if: :devise_controller?
def configure_devise_params
	devise_parameter_sanitizer.for(:sign_up) do |u|
		u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

  before_action(:authenticate_user!)
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.where(:to_do_list_id => current_user.id)
  end

  def show
    @task = Task.find_by(id: params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new
    @task.tip_id = params[:tip_id]
    @task.to_do_list_id = current_user.id

    if @task.save
      redirect_to tasks_url, notice: "Task created successfully."
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end

  def update
    @task = Task.find_by(id: params[:id])
    @task.tip_id = params[:tip_id]
    @task.to_do_list_id = params[:to_do_list_id]

    if @task.save
      redirect_to tasks_url, notice: "Task updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find_by(id: params[:id])
    @task.destroy

    redirect_to tasks_url, notice: "Task deleted."
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController

  def index
    @tips = Tip.where(:user_id => current_user.id)
  end

  def show
    @tip = Tip.find_by(id: params[:id])
  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new
    @tip.user_id = current_user.id
    @tip.title = params[:title]
    @tip.description = params[:description]
    @tip.room = params[:room]
    @tip.price = params[:price]
    @tip.saving = params[:saving]

    if @tip.save
      redirect_to tips_url, notice: "Tip created successfully."
    else
      render 'new'
    end
  end

  def edit
    @tip = Tip.find_by(id: params[:id])
  end

  def update
    @tip = Tip.find_by(id: params[:id])
    @tip.user_id = params[:user_id]
    @tip.title = params[:title]
    @tip.description = params[:description]
    @tip.room = params[:room]
    @tip.price = params[:price]
    @tip.saving = params[:saving]

    if @tip.save
      redirect_to tips_url, notice: "Tip updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @tip = Tip.find_by(id: params[:id])
    @tip.destroy

    redirect_to tips_url, notice: "Tip deleted."
  end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController

  def index
    @to_do_lists = ToDoList.all
  end

  def show
    @to_do_list = ToDoList.find_by(id: params[:id])
  end

  def new
    @to_do_list = ToDoList.new
  end

  def create
    @to_do_list = ToDoList.new
    @to_do_list.user_id = params[:user_id]

    if @to_do_list.save
      redirect_to to_do_lists_url, notice: "To do list created successfully."
    else
      render 'new'
    end
  end

  def edit
    @to_do_list = ToDoList.find_by(id: params[:id])
  end

  def update
    @to_do_list = ToDoList.find_by(id: params[:id])
    @to_do_list.user_id = params[:user_id]

    if @to_do_list.save
      redirect_to to_do_lists_url, notice: "To do list updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @to_do_list = ToDoList.find_by(id: params[:id])
    @to_do_list.destroy

    redirect_to to_do_lists_url, notice: "To do list deleted."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action(:find_user, :only => [:show, :edit, :update, :destroy])



  def find_user
    @user = User.find_by(id: params[:id])
  end



  def index
      @users = User.all
    end


  def show
    find_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]



      if @user.save
        redirect_to users_url, notice: "User created successfully."
      else
        render 'new'
      end

  end

  def edit
    find_user
  end

  def update
    find_user
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]

    if @user.save
      redirect_to users_url, notice: "User updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    find_user
    @user.destroy

    redirect_to users_url, notice: "User deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ESaver</title>


  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    #logo {
      font-family: 'Playball', serif;
      font-size: 40px;
      /*color: #FFFFFF;*/
    }

    .vinayak-box{
      padding: 7px;
      margin-bottom: 20px;
      border: 1px solid #cccccc;
      border-radius: 4px;
      background-color: #f8f8f8;
    }

    #green-box{
      background-color: #A8D800;  
    }

    #red-box{
      background-color: #E44444;
      color: #FFFFFF;
      border-radius: 8px;
    }

    #white-box{
      margin-top:75px;
      background-color: #FFFFFF;
      border-radius: 8px;
      border: 1px solid #cccccc;  
    }

    #grey{
      background-color: #f8f8f8;
    }

    #right{
      float: right;
    }

    #tabs-position{
      margin-top:16px;
    }

    #white-footer{
      background-color: #FFFFFF;
      height:40px;
      margin-top:5px;
      margin: 0 auto -20px;
    }


    body {
      background-color: #A8D800;
      padding-top: 40px;
    }

  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" id="logo">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li><a href= "/tips">Create Tips</a></li>
          <li><a href= "/tasks">Add Tips</a></li>
          <li><a href="/to_do_lists/<%= current_user.id %>">My To Do List</a></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>



  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>

  <br>

app/views/tasks/edit.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Editing Task #<%= @task.id %></h1>
</div>

<%= form_tag(task_url(@task), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :tip_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :tip_id, options_from_collection_for_select(Tip.all, :id, :title, @task.tip_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :to_do_list_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :to_do_list_id, @task.to_do_list_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Task", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

</div>

app/views/tasks/index.html.erb
 <div class="container" id="white-box">
    <br>
    <div class="row">
      <div class="col-sm-6 col-md-12">
        <div class="jumbotron">
          <div class="container">
            <h2>Add tips to your to do list</h2>
            <p>Click below to browse through tips provided by other users to add to your to do list</p>
            <p><%= link_to 'Add a New Task', new_task_url, class: 'btn btn-primary btn-lg' %></p>
          </div>
        </div>
      </div>
    </div>




<h3>Below are the tips currently on your to do list.  You can delete these tips once you have completed them.</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Tip</th>
      <!-- <th>To do list</th> -->
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.tip.title %></td>

        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, task_url(task), method: 'delete', data: { confirm: "Do you really want to delete this task?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class="container" id="white-box">

<div class="page-header">
  <h1>New Task</h1>
</div>

<%= form_tag(tasks_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :tip_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
    <%= select_tag :tip_id, options_from_collection_for_select(Tip.all, :id, :title), class: 'form-control' %>
    </div>
  </div>



  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Task", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

</div>

app/views/tasks/show.html.erb
<div class="container" id="white-box">

<div class="page-header">
  <h1>Task #<%= @task.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Tip</dt>
  <dd><%= @task.tip.title %></dd>

  <dt>To do list</dt>
  <dd><%= @task.to_do_list_id %></dd>

</dl>

</div>

app/views/tips/edit.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Editing Tip #<%= @tip.id %></h1>
</div>

<% if @tip.errors.any? %>
    <% @tip.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= message %>
        </div>
    <% end %>
<% end %>

<%= form_tag(tip_url(@tip), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name, @tip.user_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :title, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :title, @tip.title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :description, @tip.description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :room, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :room, @tip.room, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :price, @tip.price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :saving, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :saving, @tip.saving, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Tip", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
</div>

app/views/tips/index.html.erb
 <div class="container" id="white-box">
    <br>
    <div class="row">
      <div class="col-sm-6 col-md-12">
        <div class="jumbotron">
          <div class="container">
            <h2>Tips You Have Suggested</h2>
            <p>Know of a great tip for saving electricity? Post the tip and help others find ways to save!</p>
            <p><%= link_to 'Add a New Tip', new_tip_url, class: 'btn btn-primary btn-lg' %></p>
          </div>
        </div>
      </div>
    </div>





<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Room</th>
      <th>Price</th>
      <th>Saving</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= tip.user.name %></td>
        <td><%= tip.title %></td>
        <td><%= tip.description %></td>
        <td><%= tip.room %></td>
        <td><%= tip.price %></td>
        <td><%= tip.saving %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, tip_url(tip), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_tip_url(tip), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, tip_url(tip), method: 'delete', data: { confirm: "Do you really want to delete this tip?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tips/new.html.erb
<div class="container" id="white-box">

  <div class="page-header">
    <h1>Create a New Tip!</h1>
  </div>

  <h3>It's quick and easy! All you have to do is:
  <ul>
  <li>Describe your tip in the box below</li>
  <li>Rate your tip's price on a 0-5 scale</li>
  <li>Rate your tip's savings on a 0-5 scale</li>
  <li>Submit your tip for the world to see</li>
  <li>Receive a point every time someone uses your tip</li>
  </ul>
  </h3>

  <% if @tip.errors.any? %>
      <% @tip.errors.full_messages.each do |message| %>
          <div class="alert alert-dismissable alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= message %>
          </div>
      <% end %>
  <% end %>

  <%= form_tag(tips_url, method: 'post', class: 'form-horizontal') do %>

    <div class="form-group">
      <%= label_tag :title, nil, class: 'col-md-2 control-label' %>
      <div class="col-md-6">
        <%= text_field_tag :title, @tip.title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :description, nil, class: 'col-md-2 control-label' %>
      <div class="col-md-6">
        <%= text_area_tag :description, @tip.description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :room, nil, class: 'col-md-2 control-label' %>
      <div class="col-md-6">
        <%= text_field_tag :room, @tip.room, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :price, nil, class: 'col-md-2 control-label' %>
      <div class="col-md-6">
        <%= number_field_tag :price, @tip.price, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :saving, nil, class: 'col-md-2 control-label' %>
      <div class="col-md-6">
        <%= number_field_tag :saving, @tip.saving, class: 'form-control' %>

      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-6">
        <%= submit_tag "Create Tip", class: 'btn btn-primary' %>
      </div>
    </div>
</div>
<% end %>

app/views/tips/show.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Tip #<%= @tip.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>User</dt>
  <dd><%= @tip.user.name %></dd>

  <dt>Title</dt>
  <dd><%= @tip.title %></dd>

  <dt>Description</dt>
  <dd><%= @tip.description %></dd>

  <dt>Room</dt>
  <dd><%= @tip.room %></dd>

  <dt>Price</dt>
  <dd><%= @tip.price %></dd>

  <dt>Saving</dt>
  <dd><%= @tip.saving %></dd>

</dl>
</div>

app/views/to_do_lists/edit.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Editing To Do List #<%= @to_do_list.id %></h1>
</div>

<% if @to_do_list.errors.any? %>
    <% @to_do_list.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= message %>
        </div>
    <% end %>
<% end %>

<%= form_tag(to_do_list_url(@to_do_list), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name, @to_do_list.user_id), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update To Do List", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<div class="container" id="white-box">

app/views/to_do_lists/index.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>To do lists</h1>
</div>

<p><%= link_to 'Add a New To Do List', new_to_do_list_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @to_do_lists.each do |to_do_list| %>
      <tr>
        <td><%= to_do_list.user.name %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, to_do_list_url(to_do_list), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_to_do_list_url(to_do_list), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, to_do_list_url(to_do_list), method: 'delete', data: { confirm: "Do you really want to delete this to_do_list?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/to_do_lists/new.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>New To Do List</h1>
</div>

<% if @to_do_list.errors.any? %>
    <% @to_do_list.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= message %>
        </div>
    <% end %>
<% end %>

<%= form_tag(to_do_lists_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create To Do List", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Editing User #<%= @user.id %></h1>
</div>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= message %>
        </div>
    <% end %>
<% end %>

<%= form_tag(user_url(@user), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :first_name, @user.first_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :last_name, @user.last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update User", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Users</h1>
</div>

<p><%= link_to 'Add a New User', new_user_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, user_url(user), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_user_url(user), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="container" id="white-box">
<div class="page-header">
  <h1>Welcome, <%= @user.name %></h1>
</div>

<h1>Tips</h1>
<ul>
<% @user.tips.each do |tip| %>
<li><%= tip.title %> </li>
<% end %>
</ul>


<h1>Todo Tips</h1>
<ul>
  <% @user.todo_tips.each do |todo| %>
  <li><%= todo.title %></li>
  <% end %>
</ul>
</div>